<?php
	include 'header.phtml';
?>
	<div class="flex">
		<section id="bookSection">
			<h1>- Benoit Carayan - book photo -</h1>
			<figure>
				<a href=""><img src="./img/photobenoit.jpg" alt="photo_photographe"></a>
				<figcaption>Je vous présente un bref apercu du travail de <span id="figSpan">Benoit Carayan</span> artiste photographe spécialisé dans les clichés en noir et blanc.</figcaption>
			</figure>

		</section>
		<section id="slidercontainer" class="slider">
				<div class="flexslider">
					<ul class="slides">
						<li>
							<img src="img/photo_benoit/img1.jpg" alt="Photo du slider" />
						</li>
						<li>
							<img src="img/photo_benoit/img2.jpg" alt="Photo du slider" />
						</li>
						<li>
							<img src="img/photo_benoit/img3.jpg" alt="Photo du slider" />
						</li>
						<li>
							<img src="img/photo_benoit/img4.jpg" alt="Photo du slider" />
						</li>
						<li>
							<img src="img/photo_benoit/img5.jpg" alt="Photo du slider" />
						</li>
						<li>
							<img src="img/photo_benoit/img6.jpg" alt="Photo du slider" />
						</li>
						<li>
							<img src="img/photo_benoit/img7.jpg" alt="Photo du slider" />
						</li>
						<li>
							<img src="img/photo_benoit/img8.jpg" alt="Photo du slider" />
						</li>
					</ul>
				</div>
		</section>
	</div>
	<?php
	include 'footer.phtml';
	?>
