<!DOCTYPE html>
<html lang="fr">
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width,initial-scale=1">

	<title>portfolio - Arbeloa Baptiste</title>
	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" type="text/css" href="./css/flexslider.css" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
	<script src="js/jquery.flexslider-min.js"></script>
	<script type="text/javascript" charset="utf-8">
  	$(window).load(function() {
    $('.flexslider').flexslider();
	  });
	</script>
	<link rel="stylesheet" href="./css/styles.css">
</head>
<body>
	<header>
		<nav class="container" >
			<a href="./index.phtml"><img src="./img/moi.jpg" alt="photo_de_moi"></a><!--
			--><a href="./parcours.phtml" ><span class="hideNav">Formation</span></a><!--
			--><a href="./book.phtml"><span class="hideNav">Book </span></a><!--
			--><a href="./contact.phtml"><span class="hideNav">Contact</span></a>
		</nav>
	</header>
	<main>