<?php include 'header.phtml';?>
	<section>
		<div id="parcour_container">
			<div id="bar">
			  <div id="fill">
			  <h1>Html</h1>
				<p id="percent">
				  0%
				</p>
			  </div>
			</div>
			<div id="bar">
			  <div id="fill1">
			  <h1>Css</h1>
				<p id="percent1">
				  0%
				</p>
			  </div>
			</div>
			<div id="bar">
			  <div id="fill2">
			   <h1>Javascript</h1>
				<p id="percent2">
				  0%
				</p>
			  </div>
			</div>
			<div id="bar">
			  <div id="fill3">
			   <h1>Php</h1>
				<p id="percent3">
				  0%
				</p>
			  </div>
			</div>
			<div id="bar">
			  <div id="fill4">
			   <h1>Sql</h1>
				<p id="percent4">
				  0%
				</p>
			  </div>
			</div>
		</div>
	</section>
<?php include 'footer.phtml';?>